feat(toast): introduce Toast component
heroui-inc/heroui pull request #4437
Opened 2024-12-24 08:28 UTC by macci001

- Closes: #2560
- Closes: #2053
- Closes: https://github.com/nextui-org/nextui/discussions/314
- ref: #2134

## 📝 Description

## ⛳️ Current behavior (updates)

## 🚀 New behavior

## 💣 Is this a breaking change (Yes/No):

## 📝 Additional Information

2024-12-30 13:23 UTC, macci001 commented
@coderabbitai pause

2025-01-09 12:29 UTC, jrgarciadev commented on packages/components/toast/src/toast-region.tsx
> +  const [isTouched, setIsTouched] = useState(false);
@macci001 please try using a `useRef` instead so we avoid re-rendering the component when this state changes

2025-01-09 12:30 UTC, jrgarciadev commented on packages/components/toast/src/toast-region.tsx
> +  };
@macci001 move this styles to the `theme` folder

2025-01-09 12:30 UTC, jrgarciadev commented on packages/components/toast/src/toast-region.tsx
> +  const total = toastQueue.visibleToasts.length;
```suggestion
  const total = toastQueue.visibleToasts?.length ?? 0;
```

2025-01-09 12:31 UTC, jrgarciadev commented on packages/components/toast/src/toast.tsx
> +import {Spinner} from "../../spinner/src";
```suggestion
import {Spinner} from "@nextui-org/spinner";
```

2025-01-09 12:31 UTC, jrgarciadev commented on packages/components/toast/src/toast.tsx
> +import {Spinner} from "../../spinner/src";
@macci001 add the spinner as a dependency

2025-01-09 12:32 UTC, jrgarciadev commented on packages/components/toast/src/toast.tsx
> +        </AnimatePresence>
@macci001 use LazyMotion and load the dom animations dynamically

2025-01-09 15:54 UTC, macci001 commented on packages/components/toast/src/toast-region.tsx
> +  const [isTouched, setIsTouched] = useState(false);
I think we might need an state here as with ref the functionality would not work.

2025-01-09 17:52 UTC, macci001 commented on packages/components/toast/src/toast.tsx
> +import {Spinner} from "../../spinner/src";
Done

2025-01-09 17:52 UTC, macci001 commented on packages/components/toast/src/toast-region.tsx
> +  const total = toastQueue.visibleToasts.length;
Done

2025-01-10 12:22 UTC, macci001 commented on packages/components/toast/src/toast.tsx
> +        </AnimatePresence>
Done

2025-01-18 13:11 UTC, wingkwong requested changes
please update all `NextUI` and use the new name

2025-01-18 13:11 UTC, wingkwong commented on packages/components/toast/package.json
> +  "description": "adding toast",
need a better description

2025-01-18 13:11 UTC, wingkwong commented on packages/components/toast/package.json
> +  "name": "@nextui-org/toast",
please update to `@heroui/toast`

2025-01-18 13:11 UTC, wingkwong commented on packages/components/toast/package.json
> +    "@nextui-org/theme": ">=2.0.0",
since toast theme will be introduced in the latest version with one patch version bumped, any versions between `2.0.0` and that will fail.

2025-01-18 13:11 UTC, wingkwong commented on packages/components/toast/package.json
> +    "react-dom": ">=18"
please refer other packages

2025-01-18 13:11 UTC, wingkwong commented on packages/components/toast/package.json
> +    "@react-stately/utils": "3.10.5"
need to update them

2025-01-20 10:01 UTC, macci001 commented on packages/components/toast/package.json
> +  "description": "adding toast",
updated the description

2025-01-20 10:02 UTC, macci001 commented on packages/components/toast/package.json
> +    "react-dom": ">=18"
updated

2025-01-20 10:03 UTC, macci001 commented on packages/components/toast/package.json
> +    "@react-stately/utils": "3.10.5"
done

2025-01-21 18:17 UTC, jrgarciadev commented on .changeset/shaggy-beers-breathe.md
> +"@nextui-org/theme": patch
@macci001 update changesets, it should be `heroui`

2025-01-21 18:49 UTC, macci001 commented on .changeset/shaggy-beers-breathe.md
> +"@nextui-org/theme": patch
Done in: ef859cd7939e78752df630ce31b65d30187a8d3a

2025-01-27 00:56 UTC, jrgarciadev commented on packages/components/toast/README.md
> +```
@macci001 update this to @heroui/toast

2025-01-27 00:56 UTC, jrgarciadev commented on packages/components/toast/README.md
> +# @nextui-org/toast
update to heroui @macci001

2025-01-27 00:57 UTC, jrgarciadev commented on packages/components/toast/package.json
> +  "homepage": "https://nextui.org",
@macci001 update all this info to heroui - see other packages

2025-01-27 01:00 UTC, jrgarciadev commented on packages/components/toast/src/toast-region.tsx
> +  };
@macci001 wrap this function in a `useCallback`

2025-01-27 01:02 UTC, jrgarciadev commented on packages/components/toast/src/toast.tsx
> +            <motion.div {...getMotionDivProps()}>
@macci001 use `m.div` instead to avoid loading the entire library

2025-01-27 01:03 UTC, jrgarciadev commented on packages/components/toast/src/toast.tsx
> +                transition={{duration: 0.25, ease: "easeOut", delay: 0.1}}
@macci001 add prop to allow customize these values `motionProps`, see https://github.com/heroui-inc/heroui/blob/b8e7b9458672b13e0564e7fb23c3e1818f5dd606/packages/components/modal/src/modal-content.tsx#L126

2025-01-27 01:05 UTC, jrgarciadev commented on packages/components/toast/src/use-toast.ts
> +  const disableAnimation = originalProps.disableAnimation;
@macci001 use the global context as well see https://github.com/heroui-inc/heroui/blob/b8e7b9458672b13e0564e7fb23c3e1818f5dd606/packages/components/button/src/use-button.ts#L89

2025-01-27 01:05 UTC, jrgarciadev commented on packages/components/toast/src/use-toast.ts
> +
@macci001 declare these constant outside the component

2025-01-27 01:09 UTC, jrgarciadev commented on packages/components/toast/src/use-toast.ts
> +  const loadingIcon: ReactNode = props.icon;
destructure the `icon` prop and all props you don't want to pass in hte `getToastProps` otherwise we might cause the issue of `React not recognize property "icon"`

2025-01-27 01:10 UTC, jrgarciadev requested changes
@macci001 please check my comments

2025-01-27 11:47 UTC, macci001 commented on packages/components/toast/README.md
> +```
Done in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:47 UTC, macci001 commented on packages/components/toast/README.md
> +# @nextui-org/toast
Done in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:48 UTC, macci001 commented on packages/components/toast/src/toast-region.tsx
> +  };
Done in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:48 UTC, macci001 commented on packages/components/toast/src/toast.tsx
> +                transition={{duration: 0.25, ease: "easeOut", delay: 0.1}}
Added in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:48 UTC, macci001 commented on packages/components/toast/src/use-toast.ts
> +  const disableAnimation = originalProps.disableAnimation;
Done in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:49 UTC, macci001 commented on packages/components/toast/src/use-toast.ts
> +  const loadingIcon: ReactNode = props.icon;
moved in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:49 UTC, macci001 commented on packages/components/toast/src/use-toast.ts
> +
done in: 390b0bb8059fb019d2f3658a73a09c8d8147b725

2025-01-27 11:50 UTC, macci001 commented on packages/components/toast/src/toast.tsx
> +            <motion.div {...getMotionDivProps()}>
I tried using `m.div` but not sure why the drag is working only with `motion.div` and not with `m.div`.

2025-01-27 14:38 UTC, jrgarciadev commented on packages/components/toast/src/toast.tsx
> +            <motion.div {...getMotionDivProps()}>
use `domMax`

2025-01-28 12:55 UTC, wingkwong reviewed
may include more examples in docs, e.g. endContent, timeout, promise etc

2025-01-28 12:55 UTC, wingkwong commented on apps/docs/content/docs/components/toast.mdx
> +      type: "Partial<Record<\"base\" | \"content\" | \"title\" | \"description\" | \"icon\" | \"loadingIcon\" | \"progressTrack\" | \"progressIndicator\", string>>",
double check. seems more than that.

2025-01-28 13:58 UTC, macci001 commented on packages/components/toast/README.md
> +> This is an internal utility, not intended for public usage.
Done in: [4e61b92](https://github.com/heroui-inc/heroui/pull/4437/commits/4e61b924562bf5370e2f690199be272faab553d0)

2025-01-28 13:58 UTC, macci001 commented on apps/docs/content/docs/components/toast.mdx
> +      type: "Partial<Record<\"base\" | \"content\" | \"title\" | \"description\" | \"icon\" | \"loadingIcon\" | \"progressTrack\" | \"progressIndicator\", string>>",
Done in: [4e61b92](https://github.com/heroui-inc/heroui/pull/4437/commits/4e61b924562bf5370e2f690199be272faab553d0)

2025-01-30 04:58 UTC, jprosevear commented on apps/docs/content/docs/components/toast.mdx
> +      attribute: "defaultTimer",
defaultTimeout?

2025-01-30 05:13 UTC, macci001 commented on apps/docs/content/docs/components/toast.mdx
> +      attribute: "defaultTimer",
Yes, thanks @jprosevear

2025-01-30 08:18 UTC, wingkwong requested changes
1. open a toast
2. close it by clicking close button
3. see the error in console

![image](https://github.com/user-attachments/assets/3a02f8c4-e789-497b-a7f7-1ca84b125ecd)

2025-01-30 08:18 UTC, wingkwong commented on apps/docs/content/docs/components/toast.mdx
> +      type: "string",
most title in our components support ReactNode. may double check if it is feasible.

2025-01-30 08:18 UTC, wingkwong commented on apps/docs/content/components/toast/custom-styles.raw.jsx
> +          description: "Document uploaded to cloud successful.",
successfully

2025-01-30 09:32 UTC, macci001 commented on apps/docs/content/docs/components/toast.mdx
> +      default: "6000ms"
ms is not required.

2025-01-30 10:15 UTC, macci001 commented on apps/docs/content/docs/components/toast.mdx
> +      default: "6000ms"
Done in: [de5f258](https://github.com/heroui-inc/heroui/commit/de5f25846b72f908c07e31783710fba97ab3fe4c)

2025-01-30 10:20 UTC, macci001 commented on apps/docs/content/docs/components/toast.mdx
> +      type: "string",
Added in [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:20 UTC, macci001 commented on apps/docs/content/components/toast/custom-styles.raw.jsx
> +          title: "Sucessful!",
Done in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:20 UTC, macci001 commented on apps/docs/content/components/toast/custom-styles.raw.jsx
> +          description: "Document uploaded to cloud successful.",
Done in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:20 UTC, macci001 commented on apps/docs/content/components/toast/color.ts
> +import Color from "./color.raw.jsx?raw";
Done in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:20 UTC, macci001 commented on apps/docs/content/components/toast/color.ts
> +  "/App.jsx": Color,
DOne in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:21 UTC, macci001 commented on packages/components/toast/package.json
> +    "@heroui/theme": ">=2.4.6",
Done in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:21 UTC, macci001 commented on packages/components/toast/package.json
> +    "@react-stately/utils": "3.10.5"
Done in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:21 UTC, macci001 commented on packages/core/theme/src/components/toast.ts
> +export {toast, toastRegion};
DOne in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-01-30 10:21 UTC, macci001 commented on apps/docs/content/docs/components/toast.mdx
> +### Slots
Added in: [c522947](https://github.com/heroui-inc/heroui/pull/4437/commits/c522947f81169807c9de4af24ca6d807cbfd0d0f)

2025-02-11 13:01 UTC, merged